[window]
opacity = 0.97
padding.x = 5
padding.y = 5
#decorations = "None"
decorations_theme_variant = "Dark"
title = "[term]"
#title = "[alacritty]"
#title = ""

[terminal]
shell.program = "bash"
shell.args = ["-c", "screen"]
#shell.args = ["-c", "/usr/local/bin/screen"]

[font]
size = 12.0

[colors]
primary.background = "#00091a"
primary.foreground = "#fff2e6"
